spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/parking-control-db
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
jpa.hibernate.properties.hibernate.jdbc.lob.non_contextual_creation: true